---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
  - name: fedora-19
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[plex::default]
