sudo: required
dist: trusty
services:
- docker
language: ruby
rvm:
- 2.3.1
script:
- |
    if [ $SUITE != unit ]; then
      KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen test $SUITE
    fi
- |
    if [ $SUITE = unit ]; then
      bundle exec rspec
    fi
deploy:
  provider: script
  script: openssl aes-256-cbc -K $encrypted_ec1f2f0aa95a_key -iv $encrypted_ec1f2f0aa95a_iv -in .supermarket.pem.enc -out .supermarket.pem -d  && rvm $TRAVIS_RUBY_VERSION do bundle exec stove login --username meringu --key .supermarket.pem && rvm $TRAVIS_RUBY_VERSION do bundle exec stove --no-git
  on:
    tags: true
    condition: $SUITE = unit
env:
  - SUITE=unit
  - SUITE=install-centos-72
  - SUITE=install-fedora-22
  - SUITE=install-ubuntu-1604
  # TODO: These two tests fail on travis
  # - SUITE=uninstall-centos-72
  # - SUITE=uninstall-fedora-22
  - SUITE=uninstall-ubuntu-1604
  - SUITE=reinstall-centos-72
  - SUITE=reinstall-fedora-22
  - SUITE=reinstall-ubuntu-1604
